/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CoverageZone {
  'id' : bigint,
  'lat' : number,
  'lng' : number,
  'region' : string,
  'name' : string,
  'description' : string,
}
export interface Industry {
  'id' : bigint,
  'useCases' : Array<string>,
  'icon' : string,
  'name' : string,
  'slug' : string,
  'description' : string,
  'benefits' : Array<string>,
}
export interface Project {
  'id' : bigint,
  'title' : string,
  'serviceType' : string,
  'description' : string,
  'results' : string,
  'clientIndustry' : string,
  'hasBeforeAfter' : boolean,
  'industry' : string,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'features' : Array<string>,
  'icon' : string,
  'slug' : string,
  'description' : string,
  'benefits' : Array<string>,
}
export interface _SERVICE {
  'getAllIndustries' : ActorMethod<[], Array<Industry>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getCoverageZones' : ActorMethod<[], Array<CoverageZone>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];