/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Industry = IDL.Record({
  'id' : IDL.Nat,
  'useCases' : IDL.Vec(IDL.Text),
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'serviceType' : IDL.Text,
  'description' : IDL.Text,
  'results' : IDL.Text,
  'clientIndustry' : IDL.Text,
  'hasBeforeAfter' : IDL.Bool,
  'industry' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'icon' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
});
export const CoverageZone = IDL.Record({
  'id' : IDL.Nat,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'region' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllIndustries' : IDL.Func([], [IDL.Vec(Industry)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getCoverageZones' : IDL.Func([], [IDL.Vec(CoverageZone)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Industry = IDL.Record({
    'id' : IDL.Nat,
    'useCases' : IDL.Vec(IDL.Text),
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'serviceType' : IDL.Text,
    'description' : IDL.Text,
    'results' : IDL.Text,
    'clientIndustry' : IDL.Text,
    'hasBeforeAfter' : IDL.Bool,
    'industry' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'icon' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
  });
  const CoverageZone = IDL.Record({
    'id' : IDL.Nat,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'region' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllIndustries' : IDL.Func([], [IDL.Vec(Industry)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getCoverageZones' : IDL.Func([], [IDL.Vec(CoverageZone)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };